### ISSUE TITLE
Download link in documentation is broken

### ISSUE THREAD

**Issue by tanimientras** [lsc-project/documentation#2]
Hi

Seems download link in documentation is broken:

Page: https://github.com/lsc-project/documentation/blob/main/source/installation.rst
Text "You can download the package [here](https://github.com/lsc-project/documentation/blob/main/source/download)."

**Comment by coudot** [comment]
Seems all links are ok, they all go to https://lsc-project.org/download.html

Do you still have an issue?

**Comment by tanimientras** [comment]
Not anymore. thanks!
